#!/usr/bin/python

"""
Copyright (C) 2015  Luiz Fernando Oliveira, Carlos Oliveira, Matheus Fernandes

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
"""

import os
import sys
from subprocess import call

sys.stderr.write('Removing *.pyc\n')
os.system('find . -type f -name "*.pyc" -exec rm -rf "{}" \;')

pathname = os.path.dirname(sys.argv[0])
gamepath = os.path.abspath(pathname) + '/src/'
os.chdir(gamepath)
call(['python', 'main.py'])
